volumes:
  db_data:
  node_modules:

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: equipment_db
      MYSQL_USER: equipment_user
      MYSQL_PASSWORD: app_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: >
      sh -c "
      ./wait-for-it.sh db:3306 --
      python manage.py migrate &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    workdir: /code
    environment:
      DB_HOST: db
      DB_NAME: equipment_db
      DB_USER: equipment_user
      DB_PASSWORD: app_password
      DB_PORT: 3306
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      SECRET_KEY: "your_production_secret"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    command: >
      sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    workdir: /app
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    restart: always
