services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    workdir: /code
    environment:
      - DJANGO_DB_HOST: localhost
      - DJANGO_DB_NAME: equipment_db
      - DJANGO_DB_USER: root
      - DJANGO_DB_PASSWORD: root_password
      - DJANGO_DB_PORT: 3306
      - DJANGO_ALLOWED_HOSTS: "*"
      - DJANGO_SECRET_KEY: secret_key
      - DJANGO_DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
    command: >
      sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    workdir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
  volumes:
    db_data:
